version: '3.7'
services:
  apollo:
    image: apollo
    container_name: apollo
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - 8080:8080
    networks:
      - apollo-network
    privileged: true
    volumes:
      - type: bind
        source: "/Users/apollo/postgresql/data/directory"
        target: /var/lib/postgresql
      - type: bind
        source: "/Users/apollo/jbrowse/root/apollo_data"
        target: /data
      - type: bind
        source : "/Users/apollo/jbrowse/root/directory"
        target: /data/temporary/apollo_data
      - type: bind
        source : "/Users/apollo/organism"
        target: /opt/organism
    
networks:
  apollo-network:
    driver: bridge
