version: '3.7'
services:
  apollo:
    image: apollo
    container_name: apollo
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - 8080:8080
    networks:
      - apollo-network
    privileged: true
    volumes:
      - /opt/webapollo:/directory
      - /opt/webapollo:/apollo_data
      - /opt/webapollo:/directory
      - /opt/webapollo:/opt/organism    
networks:
  apollo-network:
    driver: bridge
